name: daily_calorie_calculator_flutter
description: Flutter application that allows the user to calculate the recommended daily amount of calories to gain or lose weight, based on their physical profile
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  flutter_modular: ^6.3.3
  hive: ^2.2.3
  path_provider: ^2.1.3
  dio: ^5.3.0
  result_dart: ^1.1.1
  http: ^1.1.0
  socket_io_client: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  mobx_codegen: ^2.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/articles/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
